// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5JiYV6OXFU25ldI7hL_FRADjxWCPztlA',
    appId: '1:354254852702:web:67770884cc8993aabc9acf',
    messagingSenderId: '354254852702',
    projectId: 'smarteye-b6322',
    authDomain: 'smarteye-b6322.firebaseapp.com',
    storageBucket: 'smarteye-b6322.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF2QY2rWqi8ZxABVNljiMc3r6BlHT5nzI',
    appId: '1:354254852702:android:bf0583146707b172bc9acf',
    messagingSenderId: '354254852702',
    projectId: 'smarteye-b6322',
    storageBucket: 'smarteye-b6322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHHfoIagdzoGriwVkLLzzj7nZisd9u3A',
    appId: '1:354254852702:ios:eab5e348af55cedcbc9acf',
    messagingSenderId: '354254852702',
    projectId: 'smarteye-b6322',
    storageBucket: 'smarteye-b6322.firebasestorage.app',
    iosBundleId: 'com.example.smartEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHHfoIagdzoGriwVkLLzzj7nZisd9u3A',
    appId: '1:354254852702:ios:eab5e348af55cedcbc9acf',
    messagingSenderId: '354254852702',
    projectId: 'smarteye-b6322',
    storageBucket: 'smarteye-b6322.firebasestorage.app',
    iosBundleId: 'com.example.smartEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5JiYV6OXFU25ldI7hL_FRADjxWCPztlA',
    appId: '1:354254852702:web:6341fc896c35ca39bc9acf',
    messagingSenderId: '354254852702',
    projectId: 'smarteye-b6322',
    authDomain: 'smarteye-b6322.firebaseapp.com',
    storageBucket: 'smarteye-b6322.firebasestorage.app',
  );

}